<!-- *** ASIDE login/register in case user is not connected  ***  -->
<!-- ### condition to verify is user is log ### -->
<aside>

    <img src="public/img/cadenas.svg" alt="logo representant un cadenas" class="imgLocker">
    <p>Pour accéder au tableau de scores,reprendre vos parties et ajouter des règles veuillez vous connecter</p>
    <!-- Register link -->
    <div class="ifRegisterLogin">
        <div class="ifRegister">
            <img src="public/img/register.svg" alt="logo d'inscription">
            <a href="index.php?route=register" class="btn">S'inscrire</a>
        </div>
        <!-- login link  -->
        <div class="ifLogin">
            <img src="public/img/login.svg" alt="logo de connexion">
            <a href="index.php?route=login" class="btn">Se connecter</a>
        </div>
    </div>
</aside>