<!DOCTYPE html>
<html lang="fr">

<head>
    <title>Yaniv</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="public/img/logo-complet.ico">
    <meta name="description"
        content="YANIV: Le site pour comptabiliser les points de vos parties,consulter les règles du jeu de carte Yaniv ">
    <link href="css/style.css" rel="stylesheet">
    <script src="https://kit.fontawesome.com/fe7cbf9353.js" crossorigin="anonymous"></script>


</head>

<body>
    <header>
        <?php include_once '_header.phtml'; ?>
    </header>
    <main class="container">
        <?php include $template; ?>
    </main>
    <footer>
        <?php include_once '_footer.phtml'; ?>
    </footer>
    <script src="public/js/script.js"></script>
</body>

</html>